### ISSUE TITLE
Installation failure with `--with-parallel` and `--with-gslib` on v.4.5.2.1

### ISSUE THREAD

**Issue by dreamer2368** [mfem/PyMFEM#194]
PyMFEM installation with the command
```
python3 setup.py install --with-parallel --with-gslib --user
```
fails, with the following error output:
```
/usr/tce/packages/gcc/gcc-10.3.1/bin/ld: CMakeFiles/findpts.dir/findpts.cpp.o: in function `VisualizeFESpacePolynomialOrder(mfem::FiniteElementSpace&, char const*)':
findpts.cpp:(.text+0x1bd5): undefined reference to `mfem::common::VisualizeField(mfem::socketstream&, char const*, int, mfem::GridFunction&, char const*, int, int, int, int, char const*, bool)'
/usr/tce/packages/gcc/gcc-10.3.1/bin/ld: CMakeFiles/findpts.dir/findpts.cpp.o: in function `main':
findpts.cpp:(.text.startup+0xe00): undefined reference to `mfem::common::VisualizeField(mfem::socketstream&, char const*, int, mfem::GridFunction&, char const*, int, int, int, int, char const*, bool)'
```
The full-defiled installation log is attached here: [result.log](https://github.com/mfem/PyMFEM/files/12373811/result.log)

A few things to note:
- It seems to fail in c++ MFEM compilation of the file `miniapps/gslib/field-interp.cpp`.
- v4.5.2.0 does not have this installation issue.

**Comment by sshiraiwa** [comment]
I think this is the same as what I found before (https://github.com/mfem/PyMFEM/actions/runs/5290338765/job/14322386378).
It needs to be addressed in C++ build system.

**Comment by dreamer2368** [comment]
I have compiled c++ parallel mfem with gslib before, and it didn't have a problem. Shouldn't the issue be somewhere in `setup.py` where it configures cmake command for mfem?

**Comment by NiklasFreymuth** [comment]
I encountered the same issue without the `--with-parallel` option, i.e., when just running
`python setup.py install --with-gslib`

Installing MFEM with gslib on the same machine worked perfectly fine, so the issue could be related to PyMFEM, versioning and/or the current version of the setup.py script.

**Comment by sshiraiwa** [comment]
Closing this since new version was released. ```python setup.py install --with-gslib --with-parallel --user``` should work with current 4.6.1.
Feel free to open a separate one if you have an issue with the new version.
